apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - image: codercom/code-server:latest
          imagePullPolicy: Always
          name: code-server
          env:
            - name: PASSWORD
              value: "your_password"
      nodeSelector:
        node.kubernetes.io/microk8s-worker: microk8s-worker
      restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: code-server
