apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-symbols-api-deployment
spec:
  selector:
    matchLabels:
      app: stock-symbols-api
  replicas: 5
  template:
    metadata:
      labels:
        app: stock-symbols-api
    spec:
      containers:
      - name: stock-symbols-api
        image: khant14/stock-symbols-api
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: stock-symbols-api-service
spec:
  selector:
    app: stock-symbols-api
  ports:
    - protocol: TCP
      port: 8002
