apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-symbols-api
spec:
  selector:
    matchLabels:
      app: stock-symbols-api
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-symbols-api
    spec:
      containers:
        - name: stock-symbols-api
          image: khant14/stock-symbols-api
          ports:
            - containerPort: 8002
